# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
  branches:
    include:
      - master  # or any branch you want to trigger the build from

pool:
  vmImage: 'ubuntu-latest'  # You can also use windows-latest or macos-latest

steps:
- task: Checkout@1  # Checkout the code from GitHub

- script: |
    sudo apt update
    sudo apt install openjdk-11-jdk -y  # Install Java 11 (adjust if needed)
  displayName: 'Install Java 11'

- task: Maven@3  # Use Maven to build the project
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml file
    goals: 'clean package'
    options: '-DskipTests=true'  # Optionally skip tests for faster builds

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to artifact
    artifactName: 'drop'  # Artifact name
    publishLocation: 'Container'  # Publish to the pipeline container
