# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master  # Change to your preferred branch

pool:
  vmImage: 'ubuntu-latest'  # You can also use 'windows-latest' or 'macos-latest'

steps:
- task: Checkout@1  # Checkout the code from GitHub

- script: |
    sudo apt update
    sudo apt install openjdk-11-jdk -y  # Install Java 11
  displayName: 'Install Java 11'

- task: Maven@3  # Maven build task
  inputs:
    mavenPomFile: 'pom.xml'  # Ensure the path to your pom.xml is correct
    goals: 'clean package'  # Ensure that the Maven goals are correct
    options: '-DskipTests=true'  # Optionally skip tests for faster builds

- script: |
    echo "Checking environment variables"
    echo "Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
  displayName: 'Check environment variables'

